# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [62]:
# Import NumPy as its abbreviation 'np'
import numpy as np  

In [63]:
# Create a 1-dimensional NumPy array using np.array()

arr_1=np.array([1,2,3,4,5])
print(arr_1)
# Create a 2-dimensional NumPy array using np.array()
arr_2=np.array([[1,2,3],[4,5,6]])
print(arr_2)
# Create a 3-dimensional Numpy array using np.array()
arr_3=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr_3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [64]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)

print(arr_1.shape)
print(arr_1.ndim)
print(arr_1.dtype)
print(arr_1.size)
print(type(arr_1))


(5,)
1
int32
5
<class 'numpy.ndarray'>


In [65]:
# Attributes of 2-dimensional array

print(arr_2.shape)
print(arr_2.ndim)
print(arr_2.dtype)
print(arr_2.size)
print(type(arr_2))


(2, 3)
2
int32
6
<class 'numpy.ndarray'>


In [66]:
# Attributes of 3-dimensional array
shapeOfArr3=arr_3.shape

print(arr_3.ndim)
print(arr_3.dtype)
print(arr_3.size)
print(type(arr_3))



3
int32
12
<class 'numpy.ndarray'>


In [67]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df=pd.DataFrame(arr_1)
print(df)

   0
0  1
1  2
2  3
3  4
4  5


In [68]:
# Create an array of shape (10, 2) with only ones
ones_arr=np.ones((10,2))
print(ones_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [69]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_arr=np.zeros((7,2,3))
print(zeros_arr)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [70]:
# Create an array within a range of 0 and 100 with step 3
array=np.arange(0,100,3)
print(array)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [71]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
# np.random.seed(42)
random_arr=np.random.randint(0,10,size=(7,2))
print(random_arr)

[[0 3]
 [3 4]
 [6 6]
 [3 6]
 [2 5]
 [1 9]
 [8 4]]


In [72]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_random_float = np.random.random((3, 5))
print(arr_random_float)

[[0.87146059 0.80367208 0.18657006 0.892559   0.53934224]
 [0.80744016 0.8960913  0.31800347 0.11005192 0.22793516]
 [0.42710779 0.81801477 0.86073058 0.00695213 0.5107473 ]]


In [73]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
arr_random_uniform = np.random.uniform(0, 10, size=(4, 6))
print(arr_random_uniform)


[[3.74540119 9.50714306 7.31993942 5.98658484 1.5601864  1.5599452 ]
 [0.58083612 8.66176146 6.01115012 7.08072578 0.20584494 9.69909852]
 [8.32442641 2.12339111 1.81824967 1.8340451  3.04242243 5.24756432]
 [4.31945019 2.9122914  6.11852895 1.39493861 2.92144649 3.66361843]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [74]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
randomArray=np.random.randint(1,10,size=(3,7))
# Find the unique numbers in the array you just created
theUniques=np.unique(randomArray)
print(theUniques)

[2 3 4 5 7 8 9]


In [75]:
# Find the 0'th index of the latest array you created
zeroIndex=randomArray[0]
print(zeroIndex)

[3 7 4 9 3 5 3]


In [76]:
# Get the first 2 rows of latest array you created
first2Rows=randomArray[:2]
print(first2Rows)

[[3 7 4 9 3 5 3]
 [7 5 9 7 2 4 9]]


In [77]:
# Get the first 2 values of the first 2 rows of the latest array
first2Values=randomArray[:2,:2]
print(first2Values)

[[3 7]
 [7 5]]


In [78]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

rndArr=np.random.randint(0,10,size=(3,5))
onesArr=np.ones((3,5))
print(onesArr)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [79]:
# Add the two arrays together
added_arrs=rndArr+onesArr
print(added_arrs)

[[ 3.  1.  4.  2.  8.]
 [ 4.  2.  6.  6. 10.]
 [ 4.  6.  2. 10.  2.]]


In [80]:
# Create another array of ones of shape (5, 3)

onesArr2=np.ones((3,5))
print(onesArr2)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [81]:
# Try add the array of ones and the other most recent array together
added_arrs2=onesArr2+added_arrs
print(added_arrs2)

[[ 4.  2.  5.  3.  9.]
 [ 5.  3.  7.  7. 11.]
 [ 5.  7.  3. 11.  3.]]


When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [82]:
# Create another array of ones of shape (3, 5)
onesArr3=np.ones((3,5))
print(onesArr3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [83]:
# Subtract the new array of ones from the other most recent array
# Transpose the latest array
subtractedArrays = added_arrs2- onesArr3
print(subtractedArrays)

[[ 3.  1.  4.  2.  8.]
 [ 4.  2.  6.  6. 10.]
 [ 4.  6.  2. 10.  2.]]


In [84]:
# Multiply the ones array with the latest array
multipliedArrays = onesArr3 * subtractedArrays
print(multipliedArrays)

[[ 3.  1.  4.  2.  8.]
 [ 4.  2.  6.  6. 10.]
 [ 4.  6.  2. 10.  2.]]


In [85]:
# Take the latest array to the power of 2 using '**'
power2=multipliedArrays**2
print(power2)

[[  9.   1.  16.   4.  64.]
 [ 16.   4.  36.  36. 100.]
 [ 16.  36.   4. 100.   4.]]


In [86]:
# Do the same thing with np.square()
square=np.square(multipliedArrays)
print(square)

[[  9.   1.  16.   4.  64.]
 [ 16.   4.  36.  36. 100.]
 [ 16.  36.   4. 100.   4.]]


In [87]:
# Find the mean of the latest array using np.mean()
print(np.mean(square))


29.733333333333334


In [88]:
# Find the maximum of the latest array using np.max()
print(np.max(square))


100.0


In [89]:
# Find the minimum of the latest array using np.min()
print(np.min(square))


1.0


In [90]:
# Find the standard deviation of the latest array
print(np.std(square))


32.28718355976907


In [91]:
# Find the variance of the latest array
print(np.var(square))


1042.4622222222222


In [92]:
# Reshape the latest array to (3, 5, 1)
reshapedArray=square.reshape((3, 5, 1))
print(reshapedArray)


[[[  9.]
  [  1.]
  [ 16.]
  [  4.]
  [ 64.]]

 [[ 16.]
  [  4.]
  [ 36.]
  [ 36.]
  [100.]]

 [[ 16.]
  [ 36.]
  [  4.]
  [100.]
  [  4.]]]


In [93]:
# Transpose the latest array
transposedArray=square.T
print(transposedArray)

[[  9.  16.  16.]
 [  1.   4.  36.]
 [ 16.  36.   4.]
 [  4.  36. 100.]
 [ 64. 100.   4.]]


What does the transpose do?

In [94]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
randArr1=np.random.randint(0,11,size=(3,3))
randArr2=np.random.randint(0,11,size=(3,2))
print(randArr1,randArr2)

[[9 3 7]
 [6 8 7]
 [4 1 4]] [[7 9]
 [8 8]
 [0 8]]


In [95]:
# Perform a dot product on the two newest arrays you created
dotProduct=np.dot(randArr1,randArr2)
print(dotProduct)

[[ 87 161]
 [106 174]
 [ 36  76]]


In [96]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
randArr3=np.random.randint(0,11,size=(4,3))
randArr4=np.random.randint(0,11,size=(4,3))
print(randArr3,randArr4)

[[ 6  8  7]
 [ 0  7  7]
 [10  2  0]
 [ 7  2  2]] [[ 0 10  4]
 [ 9  6  9]
 [ 8  6  8]
 [ 7  1  0]]


In [97]:
# Perform a dot product on the two newest arrays you created
# dotProduct2=np.dot(randArr3,randArr4)


It doesn't work. How would you fix it?

In [98]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
transposedofrandArr3=randArr3.T
dotProduct3=np.dot(transposedofrandArr3,randArr4)
print(dotProduct3)


[[129 127 104]
 [ 93 136 111]
 [ 77 114  91]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [99]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
randArr5 = np.random.randint(0, 11, size=(4, 3))
randArr6= np.random.randint(0, 11, size=(4, 3)) 
print(randArr5,randArr6)

[[ 6  6  7]
 [ 4  2  7]
 [ 5 10  2]
 [ 0  2  4]] [[ 2  0  4]
 [ 9  6  6]
 [10  8  9]
 [ 9  2  6]]


In [100]:
# Compare the two arrays with '>'
compare1=randArr5>randArr6

print(compare1)

[[ True  True  True]
 [False False  True]
 [False  True False]
 [False False False]]


What happens when you compare the arrays with `>`?

In [101]:
# Compare the two arrays with '>='
compare2=randArr5>=randArr6
print(compare2)



[[ True  True  True]
 [False False  True]
 [False  True False]
 [False  True False]]


In [102]:
# Find which elements of the first array are greater than 7
compare3=randArr5>7
print(compare3)

[[False False False]
 [False False False]
 [False  True False]
 [False False False]]


In [103]:
# Which parts of each array are equal? (try using '==')
comapre4=randArr5==randArr6
print(comapre4)


[[False False False]
 [False False False]
 [False False False]
 [False  True False]]


In [104]:
# Sort one of the arrays you just created in ascending order
sortedRandArr6=np.sort(randArr6)
print(sortedRandArr6)

[[ 0  2  4]
 [ 6  6  9]
 [ 8  9 10]
 [ 2  6  9]]


In [105]:
# Sort the indexes of one of the arrays you just created
sortedIndexes=np.argsort(randArr6)
print(sortedIndexes)

[[1 0 2]
 [1 2 0]
 [1 2 0]
 [1 2 0]]


In [106]:
# Find the index with the maximum value in one of the arrays you've created
max_index=np.argmax(randArr6)
print(max_index)


6


In [107]:
# Find the index with the minimum value in one of the arrays you've created
min_index=np.argmin(randArr6)
print(min_index)

1


In [108]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_indexes_axis1 = np.argmax(randArr5, axis=1)
print(max_indexes_axis1)


[2 2 1 2]


In [109]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_indexes_axis0 = np.argmin(randArr5, axis=0)
print(min_indexes_axis0)

[3 1 2]


In [110]:
# Create an array of normally distributed random numbers
normalDisArr=np.random.normal(size=10)
print(normalDisArr)

[ 2.63352822 -1.02509089 -0.78204783  0.42394307  0.8727051   2.28722598
  1.6229205   0.82373308  0.29305925  0.89663038]


In [111]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenlySpacedArr=np.linspace(1, 100, num=10)
print(evenlySpacedArr)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.